name: Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/project/emeghan
            git checkout master
            git pull origin master
            git status
            npm install
            pm2 restart Odee --update-env
            cd client
            rm -rf build
            mkdir build

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install Frontend dependecies
        run: cd client && npm install --force
      - name: Build Frontend
        run: cd client && CI=false npm run build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: "${{ secrets.USERNAME }}"
          server: "${{ secrets.HOST }}"
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          local_path: "./client/build/*"
          remote_path: "/root/project/emeghan/client/build"
          args: "-o ConnectTimeout=5"
